### ISSUE TITLE
composer Ambiguous class resolution

### ISSUE THREAD

**Issue by ontoplocal** [ventoviro/windwalker-query#3]
composer output from command "composer update"

Generating optimized autoload files
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column" was found in both "vendor/windwalker/query/Schema/Column.php" and "vendor/windwalker/renderer/Schema/Column.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Varchar" was found in both "vendor/windwalker/query/Schema/Column/Varchar.php" and "vendor/windwalker/renderer/Schema/Column/Varchar.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Date" was found in both "vendor/windwalker/query/Schema/Column/Date.php" and "vendor/windwalker/renderer/Schema/Column/Date.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Char" was found in both "vendor/windwalker/query/Schema/Column/Char.php" and "vendor/windwalker/renderer/Schema/Column/Char.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Integer" was found in both "vendor/windwalker/query/Schema/Column/Integer.php" and "vendor/windwalker/renderer/Schema/Column/Integer.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Timestamp" was found in both "vendor/windwalker/query/Schema/Column/Timestamp.php" and "vendor/windwalker/renderer/Schema/Column/Timestamp.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Datetime" was found in both "vendor/windwalker/query/Schema/Column/Datetime.php" and "vendor/windwalker/renderer/Schema/Column/Datetime.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Primary" was found in both "vendor/windwalker/query/Schema/Column/Primary.php" and "vendor/windwalker/renderer/Schema/Column/Primary.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\FloatType" was found in both "vendor/windwalker/query/Schema/Column/FloatType.php" and "vendor/windwalker/renderer/Schema/Column/FloatType.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Tinyint" was found in both "vendor/windwalker/query/Schema/Column/Tinyint.php" and "vendor/windwalker/renderer/Schema/Column/Tinyint.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Bigint" was found in both "vendor/windwalker/query/Schema/Column/Bigint.php" and "vendor/windwalker/renderer/Schema/Column/Bigint.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Double" was found in both "vendor/windwalker/query/Schema/Column/Double.php" and "vendor/windwalker/renderer/Schema/Column/Double.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Text" was found in both "vendor/windwalker/query/Schema/Column/Text.php" and "vendor/windwalker/renderer/Schema/Column/Text.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Longtext" was found in both "vendor/windwalker/query/Schema/Column/Longtext.php" and "vendor/windwalker/renderer/Schema/Column/Longtext.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Bit" was found in both "vendor/windwalker/query/Schema/Column/Bit.php" and "vendor/windwalker/renderer/Schema/Column/Bit.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Column\Decimal" was found in both "vendor/windwalker/query/Schema/Column/Decimal.php" and "vendor/windwalker/renderer/Schema/Column/Decimal.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Schema" was found in both "vendor/windwalker/query/Schema/Schema.php" and "vendor/windwalker/renderer/Schema/Schema.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\DataType" was found in both "vendor/windwalker/query/Schema/DataType.php" and "vendor/windwalker/renderer/Schema/DataType.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Schema\Key" was found in both "vendor/windwalker/query/Schema/Key.php" and "vendor/windwalker/renderer/Schema/Key.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Middleware\DbLoggingMiddleware" was found in both "vendor/windwalker/query/Middleware/DbLoggingMiddleware.php" and "vendor/windwalker/renderer/Middleware/DbLoggingMiddleware.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Middleware\DbProfilerMiddleware" was found in both "vendor/windwalker/query/Middleware/DbProfilerMiddleware.php" and "vendor/windwalker/renderer/Middleware/DbProfilerMiddleware.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\DatabaseFactory" was found in both "vendor/windwalker/query/DatabaseFactory.php" and "vendor/windwalker/renderer/DatabaseFactory.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Iterator\DataIterator" was found in both "vendor/windwalker/query/Iterator/DataIterator.php" and "vendor/windwalker/renderer/Iterator/DataIterator.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Command\AbstractTransaction" was found in both "vendor/windwalker/query/Command/AbstractTransaction.php" and "vendor/windwalker/renderer/Command/AbstractTransaction.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Command\AbstractWriter" was found in both "vendor/windwalker/query/Command/AbstractWriter.php" and "vendor/windwalker/renderer/Command/AbstractWriter.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Command\AbstractReader" was found in both "vendor/windwalker/query/Command/AbstractReader.php" and "vendor/windwalker/renderer/Command/AbstractReader.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Command\AbstractTable" was found in both "vendor/windwalker/query/Command/AbstractTable.php" and "vendor/windwalker/renderer/Command/AbstractTable.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Command\AbstractDatabase" was found in both "vendor/windwalker/query/Command/AbstractDatabase.php" and "vendor/windwalker/renderer/Command/AbstractDatabase.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Query\QueryHelper" was found in both "vendor/windwalker/query/Query/QueryHelper.php" and "vendor/windwalker/renderer/Query/QueryHelper.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoTransaction" was found in both "vendor/windwalker/query/Driver/Pdo/PdoTransaction.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoTransaction.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoHelper" was found in both "vendor/windwalker/query/Driver/Pdo/PdoHelper.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoHelper.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoReader" was found in both "vendor/windwalker/query/Driver/Pdo/PdoReader.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoReader.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoIterator" was found in both "vendor/windwalker/query/Driver/Pdo/PdoIterator.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoIterator.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoDriver" was found in both "vendor/windwalker/query/Driver/Pdo/PdoDriver.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoDriver.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Pdo\PdoWriter" was found in both "vendor/windwalker/query/Driver/Pdo/PdoWriter.php" and "vendor/windwalker/renderer/Driver/Pdo/PdoWriter.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlTable" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlTable.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlTable.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlTransaction" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlTransaction.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlTransaction.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlType" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlType.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlType.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlDatabase" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlDatabase.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlDatabase.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlWriter" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlWriter.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlWriter.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlDriver" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlDriver.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlDriver.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Mysql\MysqlReader" was found in both "vendor/windwalker/query/Driver/Mysql/MysqlReader.php" and "vendor/windwalker/renderer/Driver/Mysql/MysqlReader.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\DatabaseAwareTrait" was found in both "vendor/windwalker/query/Driver/DatabaseAwareTrait.php" and "vendor/windwalker/renderer/Driver/DatabaseAwareTrait.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\AbstractDatabaseDriver" was found in both "vendor/windwalker/query/Driver/AbstractDatabaseDriver.php" and "vendor/windwalker/renderer/Driver/AbstractDatabaseDriver.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\DatabaseDriverInterface" was found in both "vendor/windwalker/query/Driver/DatabaseDriverInterface.php" and "vendor/windwalker/renderer/Driver/DatabaseDriverInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlReader" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlReader.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlReader.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlTable" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlTable.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlTable.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlWriter" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlWriter.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlWriter.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlDriver" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlDriver.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlDriver.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlDatabase" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlDatabase.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlDatabase.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlType" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlType.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlType.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\Driver\Postgresql\PostgresqlTransaction" was found in both "vendor/windwalker/query/Driver/Postgresql/PostgresqlTransaction.php" and "vendor/windwalker/renderer/Driver/Postgresql/PostgresqlTransaction.php", the first will be used.
Warning: Ambiguous class resolution, "Windwalker\Database\DatabaseHelper" was found in both "vendor/windwalker/query/DatabaseHelper.php" and "vendor/windwalker/renderer/DatabaseHelper.php", the first will be used.

**Comment by asika32764** [comment]
Same issue as https://github.com/ventoviro/windwalker-query/issues/2
